name: kubemux
shortDesc: "Creates multiple terminal by following tail of pod logs"
longDesc: "Uses tmux>=2.1 to create multiple terminal by following tail of pod logs, each pod has a separate window and containers split by panes"
example: "./kubemux.sh"
command: "./kubemux.sh"
flags:                 
 - name: "kube"
    shorthand: "k"
    desc: "Calls the kubernetes commandline"
    defValue: "KUBE_CONFIG=default,NAMESPACE=all" 
